spring:
  datasource:
    url: jdbc:log4jdbc:h2:file:./data/mail-manager;AUTO_SERVER=TRUE
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  data:
    rest:
      base-path: /api/data
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  groovy:
    template:
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .gsp
      cache: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# SMTP 접근 제어 설정 추가
mail:
  smtp:
    allowed-ips: 127.0.0.1,12.127.176.145
    allowed-domains: localhost,jira.samsungds.net
    allowed-email-domain: samsung.com,partner.samsung.com,partner.sec.co.kr
    attachment-path: ./attachments
  batch:
    batch-size: 10
    concurrent-batch-size: 5
    lock-timeout-minutes: 1
    retry-delay-minutes: 1
    queue-processing-cron: "*/20 * * * * *"
    move-to-history-cron: "0 */20 * * * *"

logging:
  level:
    jdbc:
      sqlonly: OFF
      sqltiming: OFF
      resultsettable: OFF
      audit: OFF
      resultset: OFF
      connection: OFF

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"